# Generated by Django 4.2.7
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=200, verbose_name='Название зала')),
                ('description', models.TextField(blank=True, verbose_name='Описание тренировки')),
                ('district', models.CharField(choices=[('central', 'Центральный'), ('northern', 'Северный'), ('southern', 'Южный'), ('eastern', 'Восточный'), ('western', 'Западный')], max_length=10, verbose_name='Район')),
                ('date', models.DateField(verbose_name='Дата тренировки')),
                ('time', models.CharField(choices=[('06:00', '06:00 - 08:00'), ('08:00', '08:00 - 10:00'), ('10:00', '10:00 - 12:00'), ('12:00', '12:00 - 14:00'), ('14:00', '14:00 - 16:00'), ('16:00', '16:00 - 18:00'), ('18:00', '18:00 - 20:00'), ('20:00', '20:00 - 22:00')], max_length=5, verbose_name='Время')),
                ('max_participants', models.PositiveIntegerField(default=1, verbose_name='Максимум участников')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Текущее количество участников')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='partners.trainingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник тренировки',
                'verbose_name_plural': 'Участники тренировок',
                'unique_together': {('session', 'user')},
            },
        ),
    ]