# Generated by Django 4.2.7
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название комнаты')),
                ('district', models.CharField(choices=[('central', 'Центральный'), ('northern', 'Северный'), ('southern', 'Южный'), ('eastern', 'Восточный'), ('western', 'Западный')], max_length=10, verbose_name='Район')),
                ('interest', models.CharField(choices=[('music', 'Музыка'), ('games', 'Компьютерные игры'), ('science', 'Наука'), ('books', 'Книги'), ('parties', 'Тусовки')], max_length=10, verbose_name='Интерес')),
                ('description', models.TextField(blank=True, verbose_name='Описание чата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('active_users', models.ManyToManyField(blank=True, related_name='active_chats', to=settings.AUTH_USER_MODEL, verbose_name='Активные пользователи')),
            ],
            options={
                'verbose_name': 'Чат комната',
                'verbose_name_plural': 'Чат комнаты',
                'ordering': ['-created_at'],
                'unique_together': {('district', 'interest')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='Комната')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['timestamp'],
            },
        ),
    ]